#####################################
# configuration file for instabrain #
#####################################

# location where incoming images appears
watch_dir: /home/rewire/rt_data
# base directory for processing images
#   - defaults to watch_dir
#   - highly recommended to be in same file system
#     as watch_dir (or performance may suffer)
proc_dir: /home/rewire/rt_data

# port where summarized brain data is served
server_port: 27000

# number of anatomical slices
mprage_slices: 192

# number of functional volumes in:
# {reference functional, localizer, and neurofeedback}
epi_vols:
    rfi: 3
    loc: 480
    nfb: 480

# fwhm gaussian smoothing in mm; set to zero for no smoothing
epi_fwhm: 5

# tr in seconds
epi_tr: 1

# for Siemens scanners, converter to use for DICOMs
# currently, either dcm2nii, dcm2niix, or none (assumes .nii)
dcm_converter: none

# reference anatomical from $FSLDIR/data/standard
ref_mprage: MNI152_T1_1mm_brain

# rois from $FSLDIR/atlases
#   - name is a unique id of your choice
#   - id, atlas, and spec MUST match the XML
#     and NIFTI files supplied by FSL
#   - some sample motor cortex ROIs listed here
rois:
    - name: m1_left_a
      id: Primary motor cortex BA4a L
      atlas: Juelich
      spec: -prob-1mm

    # - name: m1_left_p
    #   id: Primary motor cortex BA4p L
    #   atlas: Juelich
    #   spec: -prob-1mm

    # - name: pm_left
    #   id: Premotor cortex BA6 L
    #   atlas: Juelich
    #   spec: -prob-1mm

    # - name: pm_right
    #   id: Premotor cortex BA6 R
    #   atlas: Juelich
    #   spec: -prob-1mm

design:
      # title of regressor
    - label: active
      # onsets in trs, starting from 1
      onsets: [19,59,99,139,179,219,259,299,339,379,419,459]
      # durations in trs, including first tr
      durations: [20,20,20,20,20,20,20,20,20,20,20,20]
      # height of regressor, out of 1
      heights: [1,1,1,1,1,1,1,1,1,1,1,1]

      # title of regressor
    - label: force
      # onsets in trs, starting from 1
      onsets: [19,59,99,139,179,219,259,299,339,379,419,459]
      # durations in trs, including first tr
      durations: [20,20,20,20,20,20,20,20,20,20,20,20]
      # height of regressor, out of 1
      heights: [0,0,.333,.333,1,1,0,0,.333,.333,1,1]

      # title of regressor
    - label: complexity
      # onsets in trs, starting from 1
      onsets: [19,59,99,139,179,219,259,299,339,379,419,459]
      # durations in trs, including first tr
      durations: [20,20,20,20,20,20,20,20,20,20,20,20]
      # height of regressor, out of 1
      heights: [0,1,0,1,0,1,0,1,0,1,0,1]
